services:
  backend:
    build:
      context: ./auction-app-backend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/auction
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD}"
      SERVER_PORT: 8080
      AUCTION_APP_JWTSECRET: "${AUCTION_APP_JWTSECRET}"
  ui:
    build:
      context: ./auction-app-ui
    ports:
      - "8090:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_BASE_URL: "${REACT_APP_BASE_URL}"
      FIREBASE_API_KEY: "${FIREBASE_API_KEY}"
    restart: always
  db:
    image: postgres:13.9
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: auction
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local