const EN_STRINGS = {
  'Footer.AboutUs': 'About Us',
  'Footer.TermsAndConditions': 'Terms and Conditions',
  'Footer.PrivacyAndPolicy': 'Privacy and policy',
  'Footer.Auction': 'AUCTION',
  'Footer.GetInTouch': 'GET IN TOUCH',
  'Navbar.Home': 'Home',
  'Navbar.Shop': 'Shop',
  'Navbar.MyAccount': 'My Account',
  'Header.Login': 'Login',
  'Header.CreateAccount': 'Create Account',
  'Navbar.InputPlaceholder': 'Try enter: Shoes',
  'Footer.CallUs': 'Call us at',
  'Home.Categories': 'CATEGORIES',
  'Home.BidNow': 'Bid now',
  'Home.NewArrivals': 'New Arrivals',
  'Home.LastChance': 'Last Chance',
  'Home.HighlightedProduct': 'Highlighted product',
  'HomeProducts.StartFrom': 'Start from',
  'Shop.SingleProduct': 'Single Product',
  'SingleProduct.StartsFrom': 'Starts from',
  'SingleProduct.HighestBid': 'Highest bid',
  'SingleProduct.NumberOfBids': 'Number of bids',
  'SingleProduct.TimeLeft': 'Time left',
  'SingleProduct.Details': 'Details',
  'SingleProduct.SellerInformation': 'Seller information',
  'SingleProduct.CustomReviews': 'Custom reviews',
  'SingleProduct.PlaceBid': 'PLACE BID',
  'SingleProduct.NoBidMessage': 'Be first to bid for this product',
  'SingleProduct.InputPlaceholder': 'Enter $56 or higher',
  'SingleProduct.InputBidError': 'You must enter price first',
  'ImagePicker.FocusedImage': 'Focused',
  'NotificationBar.HighestBidPlaced': 'Congrats! You are the highest bider!',
  'NotificationBar.Outbidded':
    'There are higher bids than yours. You could give a second try!',
  'NotificationBar.AuctionWon': 'Congratulations! You outbid the competition.',
  'NotificationBar.AuctionLost': 'Unfortunately you have been outbidded!',
};

export default EN_STRINGS;
