name: deploy-app
run-name: ${{ github.actor }} started deployment
on: [push]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v3
      - name: Run build script
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          AUCTION_APP_JWTSECRET: ${{ secrets.AUCTION_APP_JWTSECRET }}
          REACT_APP_BASE_URL:  http://ec2-3-120-228-194.eu-central-1.compute.amazonaws.com:8080/api/v1
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        run: docker-compose up -d --build && docker system prune -f
        shell: bash

        http://ec2-3-120-228-194.eu-central-1.compute.amazonaws.com/